POST http://localhost:8080/piggybanks
Accept: application/json
Content-Type: application/json

{
  "owner": "8c8c87c1-9b5f-4f73-9fa7-7f9b5c7f2296",
  "amount": 10
}

###

DELETE http://localhost:8080/piggybanks
Accept: application/json
Content-Type: application/json

{
"owner": "8c8c87c1-9b5f-4f73-9fa7-7f9b5c7f2296",
"amount": 60
}


