server:
    port: ${PORT:8090}
    servlet:
        context-path: /api/v1
    error:
        include-stacktrace: never
        include-message: never

spring:
    application:
        name: eatexpress
    sql:
        init:
            mode: always
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: validate
            # ddl-auto: create
        show-sql: true
        defer-datasource-initialization: true
        properties:
            hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:3306}/eatexpress_db
        username: user
        password: password
        driver-class-name: org.postgresql.Driver
    config:
        additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs
                    issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}
    rabbitmq:
        host: ${RM_HOST:localhost}
        port: ${RM_PORT:5672}
        username: ${RM_USER}
        password: ${RM_PASSWORD}

logging:
    level:
        com.eatexpress.app: DEBUG
        org.springframework.amqp: DEBUG
