server:
    port: ${PORT:8090}
    servlet:
        context-path: /api/v1

spring:
    application:
        name: eatexpress
    sql:
        init:
            mode: always
    jpa:
        open-in-view: false
        hibernate:
            # ddl-auto: validate
            ddl-auto: create
        show-sql: true
        defer-datasource-initialization: true
        properties:
            hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:3306}/eatexpress_db
        username: user
        password: password
        driver-class-name: org.postgresql.Driver
    config:
        additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}

logging:
    level:
        com.eatexpress.app: DEBUG
        org.springframework.amqp: DEBUG
