CREATE DATABASE IF NOT EXISTS eatexpress_db;

GRANT ALL ON eatexpress_db.* TO 'user'@'%';
GRANT SHOW DATABASES ON *.* TO 'user'@'%';
FLUSH PRIVILEGES;

CREATE SCHEMA IF NOT EXISTS restaurant;
CREATE SCHEMA IF NOT EXISTS kdg_admin;
CREATE SCHEMA IF NOT EXISTS ordering;
CREATE SCHEMA IF NOT EXISTS delivery;
